name: neom_audio_player
description: Audio Player Module for Open Neom.
version: 1.5.1
homepage: https://github.com/Cyberneom/neom_audio_player
publish_to: 'none'

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

  neom_core:
    git:
      url: git@github.com:Cyberneom/neom_core.git
  neom_commons:
    git:
      url: git@github.com:Cyberneom/neom_commons.git

  audio_service: ^0.18.18
  just_audio: ^0.10.3

  flip_card: ^0.7.0
  sliding_up_panel: ^2.0.0+1
  flutter_lyric: ^2.0.4+6

  #This would be needed when adding offline mode downloading audio.
  #metadata_god: ^1.0.

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
